# Generated by Django 6.0 on 2025-12-28 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commonnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
