# Generated by Django 6.0 on 2025-12-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dailystudylog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_screenshots',
            field=models.TextField(blank=True, help_text='Lecture screenshots/notes'),
        ),
    ]
