# Generated by Django 6.0 on 2026-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_streak_studysession_dailygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='completed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
