# Generated by Django 6.0 on 2026-01-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailygoal_completed_seconds_dailygoal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_chunked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('start_seconds', models.PositiveIntegerField()),
                ('end_seconds', models.PositiveIntegerField()),
                ('is_watched', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.video')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
    ]
