# Generated by Django 6.0 on 2026-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_video_is_chunked_videochunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudylog',
            name='daily_goal_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystudylog',
            name='goal_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_goal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
