# Generated by Django 6.0 on 2026-02-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dailystudylog_daily_goal_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_screenshots',
        ),
    ]
