# Generated by Django 6.0 on 2026-02-23 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_note_content_screenshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailystudylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.DeleteModel(
            name='CommonNote',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
